#!/bin/sh /etc/rc.common
# put this file in /etc/init.d/
USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance wireguard
    procd_set_param command /usr/bin/chisel client --auth goodweather:sfewarfgbsdfhjydgjrdt infinite-hamlet-02522.herokuapp.com 162.159.193.1:2408/udp
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_close_instance
}

